const state={token:null,companies:[],companyId:null,patients:[],appointments:[],user:null,apiUrl:localStorage.getItem("instrua_api")||"http://127.0.0.1:8080"};
const $=id=>document.getElementById(id);
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization="Bearer "+state.token;const r=await fetch(state.apiUrl+path,{...options,headers});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.message||data?.error||"Erro ao comunicar com a API.");return data}
function route(name){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(name+"Page").classList.remove("hidden");if(name==="patients")renderPatients();if(name==="agenda")loadAppointments()}
async function login(e){e.preventDefault();$("loginError").textContent="";state.apiUrl=$("apiUrl").value.replace(/\/$/,"");localStorage.setItem("instrua_api",state.apiUrl);try{const data=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});state.token=data.accessToken;state.user=data;await loadSession()}catch(err){$("loginError").textContent=err.message}}
async function loadSession(){state.companies=await api("/api/v1/companies");state.companyId=state.companies[0]?.id||null;$("loginView").classList.add("hidden");$("contentView").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");$("welcomeName").textContent="Olá, "+(state.user?.name||"usuário");$("companyInfo").textContent=state.companies[0]?.name||"Nenhuma organização disponível";if(state.companyId)await loadPatients();route("dashboard")}
async function loadPatients(){state.patients=await api("/api/v1/companies/"+state.companyId+"/patients");$("patientCount").textContent=state.patients.length;renderPatients()}
function renderPatients(){const q=($("patientSearch")?.value||"").toLowerCase();const list=state.patients.filter(p=>(p.name||"").toLowerCase().includes(q));$("patientList").innerHTML=list.length?list.map(p=>'<div class="item"><strong>'+escapeHtml(p.name)+'</strong><div class="muted">'+escapeHtml(p.phone||p.email||"Sem contato")+'</div></div>').join(""):'<div class="card">Nenhum paciente encontrado.</div>'}
async function loadAppointments(){if(!state.companyId)return;try{state.appointments=await api("/api/v1/companies/"+state.companyId+"/appointments");$("appointmentCount").textContent=state.appointments.length;$("agendaList").innerHTML=state.appointments.length?state.appointments.map(a=>'<div class="item"><strong>'+escapeHtml(a.clientName||"Paciente")+'</strong><div class="muted">'+new Date(a.startsAt).toLocaleString("pt-BR")+'</div></div>').join(""):'<div class="card">Nenhum agendamento.</div>'}catch(e){$("agendaList").innerHTML='<div class="card error">'+escapeHtml(e.message)+'</div>'}}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function logout(){state.token=null;state.user=null;$("contentView").classList.add("hidden");$("loginView").classList.remove("hidden");$("logoutBtn").classList.add("hidden")}
document.querySelectorAll("[data-route]").forEach(b=>b.addEventListener("click",()=>route(b.dataset.route)));
$("loginForm").addEventListener("submit",login);$("patientSearch").addEventListener("input",renderPatients);$("logoutBtn").addEventListener("click",logout);