const state={token:null,companies:[],companyId:null,patients:[],appointments:[],user:null,apiUrl:localStorage.getItem("instrua_api")||"http://127.0.0.1:8080"};
const $=id=>document.getElementById(id);
const api=async(path,options={})=>{const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization="Bearer "+state.token;const r=await fetch(state.apiUrl+path,{...options,headers});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.message||data?.error||"Não foi possível comunicar com a API.");return data};
const toast=msg=>{const el=$("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)};
function route(name){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(name+"Page")?.classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.route===name));$("pageTitle").textContent={dashboard:"Visão geral",patients:"Pacientes",agenda:"Agenda",instructions:"Instruções"}[name]||"Instrua";if(name==="patients")renderPatients();if(name==="agenda")loadAppointments()}
async function loadSession(){try{state.companies=await api("/api/v1/companies");state.companyId=state.companies[0]?.id||null;state.user=JSON.parse(localStorage.getItem("instrua_user")||"null");$("loginView").classList.add("hidden");$("contentView").classList.remove("hidden");$("welcomeName").textContent=state.user?.name||"Bem-vinda";$("avatar").textContent=(state.user?.name||"I")[0].toUpperCase();$("companyInfo").textContent=state.companies[0]?state.companies[0].name+" · "+state.companies[0].slug:"Nenhuma clínica disponível";if(state.companyId)await loadPatients();route("dashboard")}catch(e){logout(false)}}
async function loadPatients(){if(!state.companyId)return;state.patients=await api("/api/v1/companies/"+state.companyId+"/patients");$("patientCount").textContent=state.patients.length;renderPatients()}
async function loadAppointments(){if(!state.companyId)return;try{state.appointments=await api("/api/v1/companies/"+state.companyId+"/appointments");$("appointmentCount").textContent=state.appointments.length;const list=$("agendaList");if(!state.appointments.length){list.innerHTML='<div class="empty">Nenhum agendamento encontrado.</div>';return}list.innerHTML=state.appointments.map(a=>'<div class="patient"><div><strong>'+escapeHtml(a.clientName||"Paciente")+'</strong><div class="muted">'+new Date(a.startsAt).toLocaleString("pt-BR")+' · '+escapeHtml(a.serviceName||"Serviço")+'</div></div><span>'+escapeHtml(a.status||"—")+'</span></div>').join("")}catch(e){$("agendaList").innerHTML='<div class="empty">'+escapeHtml(e.message)+'</div>'}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderPatients(){const q=($("patientSearch")?.value||"").toLowerCase();const list=state.patients.filter(p=>(p.name||"").toLowerCase().includes(q));$("patientList").innerHTML=list.length?list.map(p=>'<div class="patient"><div class="patient-main"><div class="patient-avatar">'+escapeHtml((p.name||"?")[0].toUpperCase())+'</div><div><strong>'+escapeHtml(p.name)+'</strong><div class="muted">'+escapeHtml(p.phone||p.email||"Sem contato informado")+'</div></div></div><span class="muted">'+(p.active?"Ativo":"Inativo")+'</span></div>').join(""):'<div class="empty">Nenhum paciente encontrado.</div>'}
async function login(e){e.preventDefault();$("loginError").textContent="";state.apiUrl=$("apiUrl").value.replace(/\/$/,"");localStorage.setItem("instrua_api",state.apiUrl);try{const data=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});state.token=data.accessToken;state.user=data;localStorage.setItem("instrua_user",JSON.stringify(data));await loadSession()}catch(err){$("loginError").textContent=err.message}}
function logout(show=true){state.token=null;localStorage.removeItem("instrua_user");$("contentView").classList.add("hidden");$("loginView").classList.remove("hidden");if(show)toast("Sessão encerrada.")}
document.querySelectorAll("[data-route]").forEach(b=>b.addEventListener("click",()=>{route(b.dataset.route);$("sidebar").classList.remove("open")}));$("loginForm").addEventListener("submit",login);$("patientSearch").addEventListener("input",renderPatients);$("logoutBtn").addEventListener("click",()=>logout());$("refreshBtn").addEventListener("click",()=>state.companyId?loadSession():null);$("menuBtn").addEventListener("click",()=>$("sidebar").classList.toggle("open"));if(state.user&&state.token){loadSession()}else{$("loginView").classList.remove("hidden");$("contentView").classList.add("hidden")}if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});