spring.application.name=instrua-api

spring.datasource.url=jdbc:postgresql://localhost:5432/instrua
spring.datasource.username=instrua
spring.datasource.password=instrua_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false